2021-10-06 14:47:27,427:__main__:Failed to open the main Window
Traceback (most recent call last):
  File "c:/Users/DE1119189/Desktop/Github/Fileserve_Observer/src/main.py", line 26, in <module>
    mtain()
NameError: name 'mtain' is not defined
2021-10-06 14:50:15,421:root:Failed to open the main Window
Traceback (most recent call last):
  File "c:/Users/DE1119189/Desktop/Github/Fileserve_Observer/src/main.py", line 30, in <module>
    mtain()
NameError: name 'mtain' is not defined
2021-10-08 12:40:28,659:root:Failed to open the main Window
Traceback (most recent call last):
  File "c:/Users/Lukas/Desktop/github/Fileserve_Observer/src/main.py", line 34, in <module>
    matin()
NameError: name 'matin' is not defined
2021-10-08 12:52:02,116:__main__:Failed to open the main Window
Traceback (most recent call last):
  File "c:/Users/Lukas/Desktop/github/Fileserve_Observer/src/main.py", line 35, in <module>
    mtain()
NameError: name 'mtain' is not defined
2021-10-08 12:55:30,354:views.main_window:hat geklappt
Traceback (most recent call last):
  File "c:\Users\Lukas\Desktop\github\Fileserve_Observer\src\views\main_window.py", line 32, in __init__
    baum()
NameError: name 'baum' is not defined
2021-10-08 12:55:48,518:__main__:Failed to open the main Window
Traceback (most recent call last):
  File "c:/Users/Lukas/Desktop/github/Fileserve_Observer/src/main.py", line 31, in <module>
    main()
  File "c:/Users/Lukas/Desktop/github/Fileserve_Observer/src/main.py", line 12, in main
    sys.exit(app.exec_())
SystemExit: 0
